### ISSUE TITLE
Correct long form of MDPWS

### ISSUE THREAD

**Issue by MartinKasp** [IHE/DEV.SDPi#102]
## Section Number

- Supplement Forward Declarations
- 1:10.4.1.2 Medical Device Profile for Web Services (MDPWS)

## Priority

Low

## Issue

Acronym MDPWS not correct

## Proposed Change

Change: "Medical Device Profile for Web Services" to "Medical Devices Communication Profile for Web Services"

**Comment by ToddCooper** [comment]
SDPi Friday 24 March Review:  Minor "typo" easily corrected.
