### ISSUE TITLE
Collection of comments on Vol. 0 & 1, discussed and triaged

### ISSUE THREAD

**Issue by JavierEspina** [IHE/DEV.SDPi#107]
## Section Number

N.A. See comments in attached Word file, throughout Volumes 0 and 1.
[Service-oriented Device Point-of-care Interoperability (SDPi) Technical Framework_2023-03-27_rev.docx](https://github.com/IHE/DEV.SDPi/files/11080050/Service-oriented.Device.Point-of-care.Interoperability.SDPi.Technical.Framework_2023-03-27_rev.docx)

## Priority

Medium and Low

## Issue

The comments in the Word file are triaged and tagged as follows:
#answer - answer to Reviewer's Question
#suggestion - to be evaluated how to resolve and in which SDPi version (1.0 or later)
#fix -  to be corrected in SDPi 1.0

## Proposed Change

See #fix tags in the Word comments. In addition, see the suggestions with the #suggestion or #answer tags.

**Comment by ToddCooper** [comment]
Reviewed and updated per all comments in the collection that were labeled "#fix".

Here is the collection with updated comments:  
[Service-oriented.Device.Point-of-care.Interoperability.SDPi.Technical.Framework_2023-03-27_rev_thc1.docx](https://github.com/IHE/DEV.SDPi/files/11152295/Service-oriented.Device.Point-of-care.Interoperability.SDPi.Technical.Framework_2023-03-27_rev_thc1.docx)
