### ISSUE TITLE
IHE Wiki SDPi Pages Update Required

### ISSUE THREAD

**Issue by ToddCooper** [IHE/DEV.SDPi#149]
When searching for "IHE SDPi" the old IHE wiki pages are linked.  These were set up in 2019 November and are very outdated.

Update the content on the [IHE SDPi Profile page](https://wiki.ihe.net/index.php/DEV_SDPi_Profile).

Consider normalizing it to the [current wiki template.](https://wiki.ihe.net/index.php/Profile_Overview_Template)

ALSO update wiki pages for "DPI" and point to the confluence pages for the SDPi profiles.

**Comment by ToddCooper** [comment]
Triage Review 2024.05.07:   Update old IHE wiki pages to have a RED "banner" that indicates the page is no longer supported and add a pointer to [Gemini Device Interoperability top page](https://confluence.hl7.org/pages/viewpage.action?pageId=66926431)

**Comment by kenjfuchs** [comment]
The IHE Wiki is now updated as requested.
