### ISSUE TITLE
Define requirements for STAD 1.1 - Device is connected to the MD LAN network with a Time Source service

### ISSUE THREAD

**Issue by AnnaFeiler** [IHE/DEV.SDPi#151]
Define requirements for this basic use case. 
Time synchronization has to be good enough for a proper transmission of waveforms and real time decision making based on data from multiple devices. Suggestion: 50 ms target accuracy. Note that this has to be fulfilled by all SDC participants. 
This is a stronger constraint, than the one defined by ntp (deviations of 500 ms are defined  as unsynchronized by ntp standard).  We should also make sure (IfU), that ntp servers don't jump in time (can happen, if the server runs on a PC that also does other things and experiences high load). This can lead some minutes of unsynchronised SDC systems. 
Maybe we need to request two ntp servers to be present, with one as backup, since it seems to be normal for ntp servers not to answer every request. How much ntp configuration do we need to put into the IfU?

**Comment by ToddCooper** [comment]
Added to[ Lübeck Discussion](https://confluence.hl7.org/display/GP/2023.07.17+SDPi+1.2+Developers+Workshop).  May be in 1.1 or 1.2.
