### ISSUE TITLE
Append ToI: Discovery proxy actor 

### ISSUE THREAD

**Issue by AnnaFeiler** [IHE/DEV.SDPi#152]
ISO/IEEE 11073 SDC provides for both implicit and explicit discovery; however, for some implementations this may result in unwanted message traffic across the network; the use of a "discovery proxy" has been proposed and may be added as an optional SDPi actor.  

- [ ] Add subtasks

**Comment by ToddCooper** [comment]
Topic added to the Lübeck workshop.  Working on a prototype for upcoming PAT event (perhaps August / September.

**Comment by AnnaFeiler** [comment]
Postponed due to patent discussion.

**Comment by ToddCooper** [comment]
[SDPi Friday Review 2023.09.22](https://confluence.hl7.org/display/GP/Gemini+2023-09-22+SDPi+Friday?flashId=509963061) & [Gemini CA & Tooling 2023.09.21](https://confluence.hl7.org/display/GP/Gemini+CA+2023-09-21+Meeting) ...

MDIRA profile (over SDPi) is specifically intended to meet these questions.  The topic will be added to the [Thursday D.C. IEEE/IHE DEV meetings next week](https://wiki.ihe.net/index.php/DEV_Domain_F2F_Sep_2023_AAMI).

**Comment by ToddCooper** [comment]
**_SDPi Workshop 3 2024.06.04:_**  
Update:  Proxy has been prototyped & some companies have implemented / tested (prototype) the Discovery Proxy API.
Next Steps:  

1. Document proxy API ... TF-2 messages (abstract & concrete) -- TBD if should also be added to TF-2B MDPWS as an architectural specification
2. SDPi-P Actor Model:  Add Discovery Proxy + message exchange 

Note:  Add Stefan Dreher to Github & assign to this issue.

**Comment by ToddCooper** [comment]
Moved milestone to 1.4 based on current work by @ToddCooper  & @d-gregorczyk
