### ISSUE TITLE
Append ToI: Performance Guidelines

### ISSUE THREAD

**Issue by AnnaFeiler** [IHE/DEV.SDPi#153]
Implementations of WS-* based SDC / MDPWS may be extremely resource "hungry" adversely impacting overall SOMDS performance, especially at scale (e.g., 1000 participants on a single SOMDS).  SDPi should establish "Rules of the SDC Road" performance guidelines and expected performance levels for all participating systems. (See related Topic:  SDC for Remote & Cloud-based Connections and gRPC potential option)  ... at least a starter list of do's / don'ts!

**Comment by ToddCooper** [comment]
This guidance would go into TF2-A + Add to Lübeck discussions.

"Good SDC/SDPi Citizen" "rules of the road" etc.

**Comment by ToddCooper** [comment]
Also addresses #50
