### ISSUE TITLE
Add TimeSync related RCMs

### ISSUE THREAD

**Issue by AnnaFeiler** [IHE/DEV.SDPi#154]
Incorrect time synchronisation is considered to be a rare event, since this technologie is considered to be the established state of the art for world wide web communication. 
However, we need to consider adding requirements related to the risks of: 
- incorrect therapeutic decisions due to wrong/inaccurate time stamps - maybe add some kind of sanity check on the consumer side, if timestamps are plausible
- interruption of workflow due to misaligned clocks (devices use different ntp servers, cyber attac, imprecise synchronisation) - IfU entries on configuration of ntp (use same server), requirements for minimum accuracy of time sync.

**Comment by ToddCooper** [comment]
Added to[ Lübeck Discussion](https://confluence.hl7.org/display/GP/2023.07.17+SDPi+1.2+Developers+Workshop).  May be in 1.1 or 1.2.

**Comment by AnnaFeiler** [comment]
Suggestion: 
The Manufacturer of a SOMDS Participant SHALL include the following information in the accompanying documentation: 
-	The responsible organization needs to provide a NTP Server with 50 millisecond accuracy.
-	The responsible organization needs to provide a redundant NTP configuration with at least one backup server. 
-	TBD. Reduce likelihood of non-slewing adjustment – add settings
Note: The 50-millisecond target accuracy has proven to be suitable for highly demanding use cases like real time waveform comparison. It may not be necessary for all use cases. However, having a consistent requirement from all SOMDS Participants increases the likelihood of archiving an effective, dynamic “plug & trust” system in a MEDICAL IT network, where NTP configuration is assumed to be static. 
Note: None slewing adjustments can cause unsynchronized behavior in the system. That is why steps are taken to prevent them like having redundant NTP servers and adjusting server settings tbd. rephrase once we have the settings. 

@ToddCooper : Where in the document would I put this?
