### ISSUE TITLE
Mapping Device Information OBX-18 Equipment Instance Identifier

### ISSUE THREAD

**Issue by riechkathrin** [IHE/DEV.SDPi#18]
## Section Number

2:B.3.4.6.13 OBX-18 Equipment Instance Identifier

## Priority

High

## Issue

Currently it is not possible to identify the medical device from which the data should be sent in an HL7 message.
The UDI is not available for all devices and alternatives for uniquely identifying a device shall be defined. 

## Proposed Change

I suggest to add an extension to BICEPS pm:MdsDescriptor/pm:MetaData for the UUID of a device (as stated in https://sourceforge.net/p/opensdc/ieee11073-10207/351/ ) 
The UUID, serial number and model number can then be mapped to repeated OBX-18 segments.

**Comment by AnnaFeiler** [comment]
Can this be fixed easily in 1.0?

**Comment by ToddCooper** [comment]
> Can this be fixed easily in 1.0?

Yes, per 10 March SDPi Friday review.
