### ISSUE TITLE
Figure 3:8.7.3.17-1 is broken again

### ISSUE THREAD

**Issue by JavierEspina** [IHE/DEV.SDPi#184]
## Section Number

3:8.7.3

## Priority

Low

## Issue

The figure (physio monitor containment tree) is, once again, not displaying. What a rebellious one!
Here's what I see:
![image](https://github.com/IHE/DEV.SDPi/assets/47562907/2d11ed7b-ff49-4b0b-9710-e0a1d27710ac)

## Proposed Change

Resolve

**Comment by rhoadsj** [comment]
This is a matter of Graphvis (executable dot) not being installed (or not in the expected directory) on the local machine you are doing the build on. Plantuml needs this for many diagram types). Solution: Add the installation procedure and getting the open source Graphviz package for Mac or Windows and getting the resulting executable into the PATH to the prerequisites to doing the build.

**Comment by ToddCooper** [comment]
Issue corrected in the latest master build.
