### ISSUE TITLE
MDS/VMD identification 

### ISSUE THREAD

**Issue by d-gregorczyk** [IHE/DEV.SDPi#195]
It was agreed on the SDPi workshop/July 2023 to rephrase R0015 such that the sdpi:EquipmentIdentifier extension utilizes UUID URIs only:

R0015: For the sdpi:EquipmentIdentifier extension, a SOMDS Provider shall use URI-encoded UUIDs.

Change the profile accordingly.

**Comment by ToddCooper** [comment]
@d-gregorczyk  will update the equipment identifier section
@PeterKranich will update the gateway mapping section
