### ISSUE TITLE
Patient paths through the hospital 

### ISSUE THREAD

**Issue by AnnaFeiler** [IHE/DEV.SDPi#200]
Discuss, if it is beneficial to describe different patient paths through the hospital (planned surgery, emergency patient,...), as a precondition for identifying device coupling scenarios. If we do this, we would automatically define all of the scenarios that need to be handled at different points (ICU, OR,...) in the workflow and maybe help readers to understand the scenarios better. Present results in the Friday meeting and create a ticket, if necessary.

**Comment by ToddCooper** [comment]
There is a significant amount of "prior art" in both HL7 Patient Care WG & IHE PCC specifications.  For example, defining FHIR Workflow patterns.  Experts in those groups should be engaged for background / perspective, including Elliot Silver (ResMed & part of the HL7 DoF team) and John Donnelly (co-chair of PCC).

**Comment by AnnaFeiler** [comment]
see https://github.com/IHE/DEV.SDPi/issues/249 for follow up actions
