### ISSUE TITLE
Time synchronization for real time waveform comparison

### ISSUE THREAD

**Issue by AnnaFeiler** [IHE/DEV.SDPi#205]
Our current time synchronization is not sufficient to support real time waveform comparison. Currently, this is not a problem since this is not part of our current use cases. 
Define a synchronization mechanism for high accuracy time synchronization.

**Comment by ToddCooper** [comment]
See also the [Topic:  Precision Time Protocol Option](https://confluence.hl7.org/pages/viewpage.action?pageId=109546860)  
NTP should be sufficient for these purposes.
Issue is related to drifting clocks between the various waveform PROVIDERS, and neither PTP nor NTP address this issue.
Topic is under discussion within the SDPi community.
Release 1.x is correct.

**Comment by ToddCooper** [comment]
@PeterKranich  -- Any idea of when we should plan on resolving this issue?

**Comment by PaulMartinsen** [comment]
>  Issue is related to drifting clocks between the various waveform PROVIDERS, and neither PTP nor NTP address this issue. 

My understanding is a complete implementation of NTPv3,4 clock discipline adjusts the tick frequency of the device clock using closed-loop control. This makes me think that NTP may address drifting clocks, at least to some level.

**Comment by ToddCooper** [comment]
**SDPi Workshop #4** - 

@PeterKranich  - No longer needed given the current use of the version & counter + wave resolution.
