### ISSUE TITLE
2:B.2.1 Time Zone Setting

### ISSUE THREAD

**Issue by riechkathrin** [IHE/DEV.SDPi#206]
## Section Number

2:B.2.1 Time Zone Setting

## Priority

Medium

## Issue

R8120 states that timestamps in HL7 must be specified in local time. This is not correct. As stated in the IHE Technical Framework Volume 2 all observation times reported SHOULD be UTC, as indicated by including a time zone offset of +0000 (see  B.8.7 Time Stamps and Time Synchronization, page 137, line 3262).

## Proposed Change

As discussed in the SDPi Workshop: Remove R8120.

**Comment by ToddCooper** [comment]
2023.07.28 SDPi Friday - Keep the requirement but update indicating that when no time zone is provided, UTC should be used.  When time zone is available, then what is reported may be configurable.
