### ISSUE TITLE
Requirement R1006 is not testable

### ISSUE THREAD

**Issue by ben-Draeger** [IHE/DEV.SDPi#209]
## Section Number

Section 3:8.3.2.11.1 Amendments
https://profiles.ihe.net/DEV/SDPi/index.html#_amendments

## Priority

- *Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.*

## Issue

Requirement R1006 requires the Provider to send Reports in ascending order of the [MDIB](https://profiles.ihe.net/DEV/SDPi/index.html#acronym_mdib)'s pm:MdibVersionGroup/@MdibVersion
This Requirement is not testable as any Test Tool connecting to the Provider and observing the Reports on the Network can only tell whether or not they where RECEIVED in the ascending order of their MdibVersions. However, the order in which the messages are RECEIVED is not neccessarily equivalent to the order in which they were SEND unless the transport protocol guarantees in-order transmission (like f.i. TCP does).

As far as I understand, each SDC Report is sent via its own HTTP connection. HTTP is based on TCP, but when the Reports are sent using multiple HTTP connections, each of these connections uses its own TCP connection. Since TCP only guarantees in-order transmission of messages that are part of the same connection, TCP cannot guarantee in-order transmission of SDC reports in this case.

## Proposed Change
I would need to know more about the goal that the author of this Requirement was trying to achieve. In my eyes specifying non-observable behaviour does nor serve any purpose. When I understood the purpose, then I could think about how to achieve it without writing untestable Requirements...

**Comment by ToddCooper** [comment]
Reviewed 11.08.2023 SDPi Friday:  

1. Requirement as stated is exactly what is needed
2. Yes, there are testability challenges, but those are separate from this requirement 
3. Yes, it is testable but will require potentially significant "effort" ... but a CA Testing & Tooling question 
4. PROVIDER must ensure one connection to a CONSUMER & CONSUMER must ensure this is enabled 
5. @d-gregorczyk  will (nicely & gently) engage @ben-Draeger on understanding intent and see if there are any updates to the SDPi specification (e.g., a requirement Note:) that should be added

**Comment by d-gregorczyk** [comment]
I looked into the SDPi spec and found this here:

```
R1001 : A SOMDS Provider shall only establish one TCP connection at a time for every subscribed SOMDS Consumer.
```

This should do the trick. However, we do not take HTTP pipelining into consideration. I try to come up with a requirement to prevent use of pipelining for subscriptions.
