### ISSUE TITLE
Prohibit XML Mixed Content and QName values in extensions

### ISSUE THREAD

**Issue by d-gregorczyk** [IHE/DEV.SDPi#210]
Extensions shall not contain

- _XML mixed content_ as it poses increased complexity in processing data, and by that unneccessarily complicating verification measures
- _QNames_ in values as QNames pose a leaky abstraction and can make it impossible to be processed correctly due to loss of XML namespace prefix information

**Comment by d-gregorczyk** [comment]
Example:

The following two excerpts are not equal

```xml
<pre:Content><pre:Child attr="foobar"/>Some<pre:Child2/> more text</pre:Content>
```

```xml
<pre:Content><pre:Child attr="foobar"/>Some more<pre:Child2/>text</pre:Content>
```

However, some libraries do not distinguish between the one or the other and merge multiple text nodes to one text node.

**Comment by ToddCooper** [comment]
Reviewed SDPi Friday 11.08.2023 ...

1. Agreed with issues & resolution
2. @d-gregorczyk  to add requirements to TF-2A for release 1.2  (include example(s) in requirement note(s))
