### ISSUE TITLE
How to model compound metrics in SDC

### ISSUE THREAD

**Issue by PeterKranich** [IHE/DEV.SDPi#228]
SDC does not have the concept of a compound metric. An example of a compound metric is the blood pressure which consists of the three individual components systolic, diastolic, and mean blood pressure.

One proposal is to model a compound metric as a channel. However, this requires more information whether this is a common metric channel or a compound metric channel. It is also not defined where in the data model the code for entire compound metric (e. g. BP for the blood pressure compound) shall be set.

Another proposal is to model the compound metric with the pm:Relation attribute of the individual components in the compound metric. E. g. the BPsys would have pm:Relation\@Entries to the BPdia and BPmean with the pm:Relation\@Code of the BP compound metric.

There is a need to discuss, find a consense, and define how compound metrics shall be modelled in SDC.

**Comment by ToddCooper** [comment]
SDPi Friday 2023.10.27 - Reviewed and scheduled for 1.2.    Add to the 2023.11.10 Agenda

Note:  SSch mentioned use "relation" for this kind of compound coupling.  e.g., "SST"  (Set of Summary Statistics) would be a good option.  The "relation code" could be for BP.    Challenges would include how to factor in "breath cycle", which may impact the wording of the SST in the BICEPS update.  

Team would include Martin, David, Peter, Stefan, Göran Frank.  May pull in others especially for ventilation related compound numerics.

**Comment by ToddCooper** [comment]
Note:  Team discussion is planned for 15 November with a report out in the subsequent 17 or 24 SDPi Friday meetings.

**Comment by PeterKranich** [comment]
We should also talk about the state updates of compound metrics and how the different states can be related to one measurement.

**Comment by PeterKranich** [comment]
Discussion took place on 22-Nov-2023. 
Attendees: @d-gregorczyk, @MartinKasp, @schlich09, and @PeterKranich 

MDIB Descriptor:
- For compound metrics, the pm:Relation element of the pm:AbstractMetricDescriptor shall be used to group the individual metrics belonging to the same compound metric together.
- The pm:Relation/@Kind shall be set to "SST".
- The pm:Relation/@Entries shall list the handles of the other metrics belonging to the same compound metric
- pm:Relation/pm:Code shall be set to the coded term of the compound metric on all metrics belonging to the same compound metrics

Example - Non-invasive Blood Pressure:

- NiBP systolic metric: @Handle="NiBP.sys", pm:Type/@Code= MDC_PRESS_BLD_NONINV_SYS, pm:Relation/pm:Code/@Code=MDC_PRESS_BLD_NONINV, pm:Relation/@Kind="SST", pm:Relation/@Entries="NiBP.dia,NiBP.mean"
- NiBP diastolic metric: @Handle="NiBP.dia", pm:Type/@Code= MDC_PRESS_BLD_NONINV_DIA, pm:Relation/pm:Code/@Code=MDC_PRESS_BLD_NONINV, pm:Relation/@Kind="SST", pm:Relation/@Entries="NiBP.sys,NiBP.mean"
- NiBP mean metric: @Handle="NiBP.mean", pm:Type/@Code= MDC_PRESS_BLD_NONINV_MEAN, pm:Relation/pm:Code/@Code=MDC_PRESS_BLD_NONINV, pm:Relation/@Kind="SST", pm:Relation/@Entries="NiBP.sys,NiBP.dia"

State:

- To indicate in the metric state that metric values from the individual metrics belonging to the same compound metric and the same measurement episode, either the @DeterminationTime of all values, or in the case of a pm:NumericMetricValue the @StartTime (and propably also the @StopTime) of all values shall be set to the same timestamp for start and stop
- If the @StartTime (and probably also the @StopTime) of all values is the same for start and stop, the @DeterminationTime may be different.

**Comment by ToddCooper** [comment]
SDPi Friday 2024.02.02 - Move to create a branch & PR for this.  Add to core 1.3 release capabilities.  (@PeterKranich  to do)
