### ISSUE TITLE
Context-sensitive requirements

### ISSUE THREAD

**Issue by MartinKasp** [IHE/DEV.SDPi#23]
## Section Number

Entire document

## Priority

Low to high ;-)

## Issue

Some requirements are context-sensitive to the chapter/annex the belong to. Thus, when you only get rie requirement, it can be misleading. For example: R1002 forbids UPD connections (except for ad-hoc discovery). However, this is only valid for the MDPWS binding. Thus, you have to know that R1002 is part of appendix A to understand it. The requirement will not apply for, e.g., BICPES-over-CoAP.

## Proposed Change

Intended fix: In general, we should aim for requirements that can be interpreted unambiguously without context or that the context is always clear. Options: Rephrase requirements; introduce requirement number prefixes that clarify the context unambiguously.

**Comment by ToddCooper** [comment]
Note this may also include a requirement permalink discussion as well.

**Comment by ToddCooper** [comment]
Added to the workshop agenda  page

**Comment by ToddCooper** [comment]
Developer's Workshop 2023.07.21 Discussion:

1. Add an initial set of requirement metadata labels to scope / group the requirement
2. Render the label in the requirement boxes (somewhere discreet but visible)
3. Document approach in the _**TF-1 Appendix A.6 SDPi Requirements Modeling & Integration**_ section
4. Add at the same time that the RI linkages will be added (See Issue #8

**Comment by ToddCooper** [comment]
**SDPi Workshop 3 2024.06.04:** 
Reaffirmed the July 2023 resolution above.
Note:  The need is after foundational requirement linkages are implement. 
For example, if an optional transport is provided (e.g., gRPC) this labeling **may** be valuable.

DECISION: Close issue until some time in the future when it MAY be needed.
