### ISSUE TITLE
Import results of the clinicians workshop

### ISSUE THREAD

**Issue by AnnaFeiler** [IHE/DEV.SDPi#249]
We expect the workshop to lead to a first patient journey (planned surgery) beeing available. This includes: 
- Clinical challenges that can be solved by interoperability
-  User requirements for further use case development 
-  Well defined clinical benefits of the use case to enable risk benefit analysis
- Potentially, further UX research related questions that need to be solved as a follow up.

Please transfer the workshop results into our ticket system: 
- The following content needs to be integrated in SDPi: Use cases including clinical benefits , requirements (if those are already available) and the journey itself 
- User requirements that need to be solved from the technical side need tickets
- Follow up tickets (UX research, additional journeys)

**Comment by jonasroth1** [comment]
I think what we ended up with from the clinicians workshop is more the foundation for further discussions than actual results that can be implemented into GitHub issues. So I would close that ticket for now and suggest we open that in Github again, when there are new developments and further discussions or workshops
