### ISSUE TITLE
HL7 2024-May:   Alert Requirements still under development

### ISSUE THREAD

**Issue by ToddCooper** [IHE/DEV.SDPi#294]
## Section Number

All sections 

## Priority

- *Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.*

## Issue
[HL7 MAY2024 Ballot Comment:  OTHER-2815 "Alert Requirements still under development" 
](https://jira.hl7.org/browse/OTHER-2815) 

_Standards referenced in the standard are to be developed (2024/2025) and may affect the use of them in this standard
Unknown Alert requirements may not be fully supported_

## Proposed Change

Informative text will be added to the specification clearly indicating that some referenced standards that are in development may result in requirements changes once they are published.

This includes updating the content in the ...

- Document's introductory material
- Referenced standards section (TF-1B).

**Comment by JavierEspina** [comment]
Beyond such informative statement (as proposed in "Propose change") would it make sense / help to also state that the current version of SPDi does not use [IEEE 11073-10702:202x] content (incl. any of its requirements)? Not sure if that would address the comment raised in https://jira.hl7.org/browse/OTHER-2815...

**Comment by ToddCooper** [comment]
> Beyond such informative statement (as proposed in "Propose change" above), would it make sense / help to also state that the current version of SPDi does not use [IEEE 11073-10702:202x] content (incl. any of its requirements)? Not sure if that would address the comment raised in https://jira.hl7.org/browse/OTHER-2815.
> 
> The same could be said for [IEEE 11073-10703:202x], as external control sections / text are even more of a placeholder.

I believe this was a general approach to addressing this "building it while your flying it" issue.  Did we have a separate Github Issue with this general comment?  

That said, Yes, I agree 100% ... and of course ... go for it, @JavierEspina !!!
