### ISSUE TITLE
Inconsistent actor references and links

### ISSUE THREAD

**Issue by MaryLJ** [IHE/DEV.SDPi#3]
## Section Number

*References and links to specific IHE actors throughout the supplement*

## Priority
- *Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.*

## Issue

*When referring to a specific IHE actor (e.g., SOMDS actor), the word actor should be capitalized; however, sometimes the word actor is dropped completely like in Section 10.1.1.3 (IHE prefers to drop the word "actor" after the name except in instances where it is needed for clarity).

The supplement is inconsistent in this regard. Sometimes actor follows the actor name, sometimes not.

Also, the link text to an actor is sometime italicized and sometimes not*

## Proposed Change

*- Decide on how you want to refer to actors and be consistent throughout the document (recommendation is to remove the word "actor" except in cases where is is need for clarity (like in this sentence from Section 10.1.1.4  "A SOMDS Connector can implement both SOMDS Consumer and SOMDS Provider actors.)*
*- Decide if links to specific actors should be italicized and be consistent throughout the document*
![image](https://user-images.githubusercontent.com/25642425/219718654-a7a1580b-5b2a-49c8-9bd8-18e39a6cbf14.png)

**Comment by MaryLJ** [comment]
The actor case issue was resolved with the MLJ-prepub-edits branch but "Decide if links to specific actors should be italicized and be consistent throughout the document" is still open

**Comment by ToddCooper** [comment]
Decision:  Not to italicize.

This will be addressed in #99
