### ISSUE TITLE
ProbeMatch behaviour potentially inconsistent

### ISSUE THREAD

**Issue by JavierEspina** [IHE/DEV.SDPi#317]
## Section Number
2:3.47.4.4.1 Trigger Events

## Priority
Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

## Issue
Why is the ProbeMatch message in DEV-47 sent with "zero or more" scope matches whereas in DEV-24 it is sent with "a match"?

## Proposed Change
To clarify or correct

**Comment by ToddCooper** [comment]
**SDPi Friday 2024.10.04** - 
Javier reviewed the question and whether this is a technical issue to be resolved or a documentation issue (for clarity) or a non-issue.  Group determined that it was not an issue for 1.4.1 publication, but should be discussed by SDC technical experts (primarily @d-gregorczyk ) and any changes folded into 2.0.

**Comment by ToddCooper** [comment]
**SDPi Friday 2024.10.11** -
@d-gregorczyk  confirmed that in Managed Mode, a response is required, even if it is "zero". 
DECISION:  Add a note to DEV-47 to clarify this behavior (@JavierEspina will add).
