### ISSUE TITLE
SOMDS ACM gateway Actor definition comments

### ISSUE THREAD

**Issue by spokrwilder** [IHE/DEV.SDPi#323]
Section 1:12.1.1

Medium Priority

## Issue
ACM alert communication is unsolicited by the AM actor and requires no prior subscription by the AR actor.  A subscribe model (which is described as part of the SOMDS ACM gateway Actor in section 1:12.1.1)would presume either all AMs would know all ARs or all ARs would know all AMs.  This seems an impractical goal.  

## Proposed Change
Rather than polling/query, unsolicited communication provides the most near real time responsive approach to communicating medical device alarms and is the current method used in DEV ACM transactions.

**Comment by ToddCooper** [comment]
**SDPi Friday 2024.10.18 Review** - 
Group review and discussion resulted in the following:

1. The referenced section + subsequent section on the ACM Gateway ([1:12.1.1.3 SOMDS ACM Gateway](https://profiles.ihe.net/DEV/SDPi/index.html#vol1_clause_sdpi_a_somds_acm_gateway)) does not address adding a pub/sub paradigm to the ACM AM side of the gateway; the referenced section is focused on how the SDC-based alerting is supported, providing both a polled & event based mechanism per the SDC standards; 
2. The ACM AM side of the gateway will function just as it does in all ACM AM actor implementations, namely with async / unsolicited PCD-04 transactions per IHE DEV TF-2 specifications;
3. The SDPi TF-2B ACM Gateway specification maps the semantics of the SDC alerts (per 11073-10207) to ACM message contents, but is driven by receipt of SDC alert information on that side of the gateway.

NOTE:  Planned but still missing from the 1:12.1.1.3 SOMDS ACM Gateway section is a sequence diagram that makes it clear how the SDC alerting "events" trigger PCD-04 transactions.  Adding this content (diagram + explanation) should make the interactions much clearer.  

**DECISION**:  Update the specification (for 2.0 release) to include clear explanation of the functioning of the ACM Gateway and how it seamlessly integrates the SDC and ACM ecosystems.

**Comment by spokrwilder** [comment]
Thanks for the team review and comments Todd.  The responses above make sense and I agree with the decision on actions to take. I think the sequence diagram will go a long way toward helping with confusion on that subject.  Looking forward to seeing that when added.

**Comment by ToddCooper** [comment]
**IHE ALL DEV Review 23.10.204** - 
Reviewed the two ACM issues and realized that this one had been closed prematurely.  Reopening the issue until it is closed upon the related PR approval and updates merged back to Master.

**Comment by ToddCooper** [comment]
Workshop #4 Discussion - 
Not clear that a diagram will help, given the number of potential triggers for a PCD-04.  Simply adding descriptive content may be sufficient.
