### ISSUE TITLE
R8101 Multiple messages for operating modes, that could be available 

### ISSUE THREAD

**Issue by AnnaFeiler** [IHE/DEV.SDPi#33]
## Section Number

TF.2 B.3 R8101

## Priority

- *Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.*

## Issue

"R8101
If the MDIB contains several MDS elements that could operate in different pm:MdsState/@OperatingMode states, there
shall be a separate [PCD-01] message per MDS."

@MartinKasp : Do we really need separate messages of it is only possible that there are different operating modes, or is it only necessary if this is actually the case? I would assume the second case.
@PeterKranich : The HL7 MSH (Message Header) contains the Processing Id with the code whether the data are production or test data. The MSH only exists once per message.

## Proposed Change

Keep current text.

**Comment by PeterKranich** [comment]
Discussed at the SDPi workshop on 20-Jul-2023 in Luebeck:
* Follow proposal and keep current text
