### ISSUE TITLE
Coded Value Mapping: missing CodingSystemVersion

### ISSUE THREAD

**Issue by riechkathrin** [IHE/DEV.SDPi#54]
## Section Number

Appendix 2:B Gateways

## Priority

Medium

## Issue

The mapping of Coded Value elements is inconsistent. The information about the CodingSystemVersion is only mapped within a translation.

## Proposed Change

I suggest to always map the CodingSystemVersion information if available.

**Comment by ToddCooper** [comment]
Added back "Comment NEW" until issue has been reviewed by the group on SDPi Friday calls.

**Comment by ToddCooper** [comment]
10 March SDPi Friday review:  Agreed with the 1.1 milestone assignment.
