### ISSUE TITLE
Volume 3: specify how MDC/IEEE 11073-10101 private codes are defined in the MDIB

### ISSUE THREAD

**Issue by PeterKranich** [IHE/DEV.SDPi#57]
## New section in volume 3

Missing definition

## Priority

- *Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.*

## Issue

The BASE-PKP requirement TR1358 is not very precise on how to define private MDC/IEEE 11073-10101 codes in the MDIB:
TR1358: If an SDC BASE PARTICIPANT uses a private code as detailed in [IEEE 11073-10101], the SDC BASE PARTICIPANT SHALL refer to its definition by providing a pm:Translation with a @CodingSystem that uniquely identifies the private coding system that contains the code.

## Proposed Change

Volume 3 shall contain a section that details the requirement above:
* pm:Translation must contain exactly one entry with the same code and the CodingSystem of the device manufacturer
* Recommendation how to define a unique devive manufacture CodingSystem for MDC private codes
* Note that pm:Translation could also contain other alternative codes (e. g. LOINC, SNOMED, etc.) but only one entry with the private MDC code. This entry may not the first one in the list.

**Comment by AnnaFeiler** [comment]
Relates to https://github.com/IHE/DEV.SDPi/issues/9

**Comment by ToddCooper** [comment]
@AnnaFeiler - Please do not remove the "Comment NEW" labels until we have had a chance to review it as a group on our SDPi Friday calls.  Adding labels / changing initial labels is fine.  Thanks!

**Comment by ToddCooper** [comment]
10 March SDPi Friday review:  Agreed for 1.1; update existing section: 

3:8.3.2.5 Nomenclature Considerations – Private Extensions & External Systems

**Comment by PeterKranich** [comment]
@AnnaFeiler: it relates to #9 and #58 but at a different level. This issue is independent of the gateway mappings. The goal is to describe the usage of MDC private codes in the MDIB more precisely. #9 and #58 is about how to map the information from MDIB to HL7.

**Comment by riechkathrin** [comment]
See #106.
"Recommendation how to define a unique devive manufacture CodingSystem for MDC private codes" is still missing.

**Comment by ToddCooper** [comment]
See Topic of Interest:  [Topic: Guidelines for globally unique vendor-specific coding system identifier ](https://confluence.hl7.org/display/GP/Topic%3A+Guidelines+for+globally+unique+vendor-specific+coding+system+identifier)

**Comment by PeterKranich** [comment]
@ToddCooper, @d-gregorczyk: I added a resolution proposal to the ToI (see link above).
