### ISSUE TITLE
Contradictory requirements for translation

### ISSUE THREAD

**Issue by riechkathrin** [IHE/DEV.SDPi#58]
## Section Number

2:B.4.4.2.7 PID-10 Race

## Priority

- Medium

## Issue

The mapping of the MDC private codes specifies that if a private code exists, the corresponding translation must be mapped. In the case of PID-10, however, the first translation that is found is to be mapped. What happens if there is a private code in PatientDemographics/Race?

## Proposed Change

Remove comment in Table 2:B.4.4.2.7-1. PID-10 Race Mapping that restricts the mapping to the first translation.

**Comment by AnnaFeiler** [comment]
Since this is the third issue related to translations, maybe we can discuss a quick fix and solution in the friday call. The related issues are: #9 and #57
