### ISSUE TITLE
Few unlabelled shall statements

### ISSUE THREAD

**Issue by JavierEspina** [IHE/DEV.SDPi#68]
## Section Number

2:3.23.5.4 Security Requirements & Considerations

## Priority

Medium

## Issue
"Appropriate security risk management **shall** be performed to ensure that no unintended information is disclosed during UNSECURED message exchange" -> Question for the SDPi group: is this shall statement (outside of a labelled requirements box) acceptable in view of the RI+MC+RR ambitions?
Note that this applies to all "Security Requirements & Considerations" sections (for all transactions) in Chapter 2:3.

## Proposed Change

Do like for most other requirements (labelled and in a box).

**Comment by d-gregorczyk** [comment]
I would like to rephrase the sentence such that the requirement keyword disappears. Currently, the text is included by using the asciidoc include directive. Transforming the text into a req box would cause dozens of replicated requirement numbers. If we would create separate requirements, we would have many requirements of the same flavor. By removing the shall, we still make it visible to the reader that actions have to be taken into account.

**Comment by d-gregorczyk** [comment]
Suggestion: 

> Appropriate security risk management is performed to ensure that no unintended information is disclosed during UNSECURED message exchange

**Comment by JavierEspina** [comment]
I agree with the reformulation David proposed.

**Comment by ToddCooper** [comment]
To make it read "better", "performed to ensure" was tweaked to "performed in order to ensure".

**Comment by JavierEspina** [comment]
Resolution looks fine now, after an additional commit to PR #125 . Will wait for that PR to close this issue.
