### ISSUE TITLE
Unclear traceability of BICEPS Services requirement

### ISSUE THREAD

**Issue by JavierEspina** [IHE/DEV.SDPi#70]
## Section Number

2:3.25.4.2.2 Message Semantics

## Priority

Low

## Issue

Unclear traceability of BICEPS Services requirement "GET SERVICE (mandatory)" 

## Proposed Change

Mention here that the mandatory nature of GET SERVICE comes from BICEPS. This will prevent confusion when reading R0500 in Vol2:A (which mandates more that just that one service) and hence clarify what the requirement of THIS spec is.

**Comment by d-gregorczyk** [comment]
Add a note to R0500 to clarify the reason for having it and refer to GET SERVICE to be mandatory anyway.
