### ISSUE TITLE
Unclear need for DEV-28

### ISSUE THREAD

**Issue by JavierEspina** [IHE/DEV.SDPi#75]
## Section Number

2:3.28 

## Priority

Medium

## Issue

It is unclear why DEV-28 is needed (vs. already integral part of DEV-27 [Notification message])

## Proposed Change

Clarify

**Comment by ToddCooper** [comment]
SDPi Friday 24 March - @ToddCooper  work with @JavierEspina  to understand the lack of ... clarity.
