### ISSUE TITLE
Unclear need for DEV-29

### ISSUE THREAD

**Issue by JavierEspina** [IHE/DEV.SDPi#76]
## Section Number

2:3.29 

## Priority

Medium

## Issue

It is unclear why DEV-29 is needed (vs. already integral part of DEV-27 [Notification message]).

## Proposed Change

 If not needed, remove transaction. If needed explain duplication (e.g. with a "flame note" as done for DEV-35/36)

**Comment by ToddCooper** [comment]
SDPi Friday 24 March Review - They are different primarily based on the content that is exchanged and thus their purpose.  @ToddCooper  will work with @JavierEspina  to update text to add clarity.
