### ISSUE TITLE
Inconsistency in Probe message semantics

### ISSUE THREAD

**Issue by JavierEspina** [IHE/DEV.SDPi#79]
## Section Number

2:A.2.2.1.4 Message Semantics

## Priority

Medium

## Issue
"s12:Envelope/s12:Body/wsd:Hello/wsd:Scopes/@MatchBy"-> In the message outline above, I can't see the "Hello" inside the "Body". Is this correct/consistent? The same comment applies to the 2-3 lines below (within this section).

## Proposed Change

Clarify / Correct

**Comment by d-gregorczyk** [comment]
Copy paste issue, I guess. I'm going to fix the element paths.
