### ISSUE TITLE
Referenced standards in ProbeMatch message

### ISSUE THREAD

**Issue by JavierEspina** [IHE/DEV.SDPi#80]
## Section Number

2:A.2.2.2.1 Referenced Standards

## Priority

Low/Medium

## Issue

MDPWS is also referenced. Why not add it ? (maybe add both 20701 and 20702, as done in the Probe Message section). This comment applies to the sections of ProbeMatch, (Resolve?) and ResolveMatch.

## Proposed Change

Ditto

**Comment by d-gregorczyk** [comment]
DEV-24: add references to 20701 and 20702 (as done in DEV-23)
Also: Put scope "sdc.mds.pkp:1.2.840.10004.20701.1.1" from DEV-24 (ProbeMatch) to DEV-23 (Hello).

**Comment by d-gregorczyk** [comment]
Resolve is independent of 20701 and 20702, however, I missed to add them to ResolveMatch. Will do now.

**Comment by JavierEspina** [comment]
Comment fully resolved now

**Comment by ToddCooper** [comment]
Issue resolved in PR #109
