### ISSUE TITLE
Use of "this profile" in security consideration notes

### ISSUE THREAD

**Issue by JavierEspina** [IHE/DEV.SDPi#86]
## Section Number

2:A.3 Security Considerations

## Priority

Low

## Issue

The two instances of "this profile" in these two paragraphs should rather read "these profiles" or "the SDPi profiles", as this appendix is not specific to a profile. 

## Proposed Change

Ditto

**Comment by d-gregorczyk** [comment]
I disagree, it is meant to be "this profile", which refers to SDPi. Should I rather write this specification rather than profile to make that clear?

**Comment by ToddCooper** [comment]
SDPi Friday 24 March Review - Agreed to change to "this specification" since "profile" would point to one of four or a subset.

**Comment by JavierEspina** [comment]
I agree with the resolution. Looking at its implementation I think it was not necessary to replace "profile" with "specification" in all cases, as that was only needed in the common sections that don't deal with a single SDPi profile. However I have no strong feeling about this. So no clear need for additional changes.
