### ISSUE TITLE
Confusing SHALL in R0003

### ISSUE THREAD

**Issue by JavierEspina** [IHE/DEV.SDPi#87]
## Section Number

2:A.4.1.2.1 Default Priority Group

## Priority

Medium

## Issue

This shall statement is a bit confusing w.r.t. its applicability scope. Does it always apply or only for those that decide to use the Consumer-Controlled Delay approach? Or not even that? (Note that "2:A.4.1 Connection Time Delay" presents all this as options that can be used...so Shall statements are surprising if their conditionality is not clearly delimited)

## Proposed Change

Clarify / Correct

**Comment by d-gregorczyk** [comment]
This does apply in case the manufacturer decides against explicit configuration of a priority group on installation or during operation. But it does apply for every consumer, according to sdc:Glue:

> R0076: An SDC SERVICE CONSUMER SHALL delay to send the first HTTP(S) MESSAGE regardless of the type to an endpoint after an implicit discovery [...]

So even if it appears to be an option, it is mandated by sdc:Glue. If we want to make it optional, we have to supersede it in SDPi.

I phrased the whole section as defensive as possible as I am not a fan of the priority groups and like to see a different approach for network load balancing in the future. For now, we stick to the standard, which does not offer any options other than doing it.

**Comment by ToddCooper** [comment]
SDPi Friday 24 March Review:  TBD whether this is a 1.0 or 1.1 issue.
