### ISSUE TITLE
Wrong table labels

### ISSUE THREAD

**Issue by JavierEspina** [IHE/DEV.SDPi#89]
## Section Number

2:B.3.4.1.1 MSH-11 Processing ID

## Priority

Low

## Issue

"Table 2:B.4.4.1.1-1 defines the mapping..." -> The table labels (at least in this DEC Gateway section) are inconsistent when referenced vs their caption label. The 2:B:3 is turned into 2:B:4.

## Proposed Change

Correct throughout 2:B:3 (DEC) and 2:B:4 (ACM)

**Comment by ToddCooper** [comment]
SDPi Friday 24 March Review:  @d-gregorczyk  will review issue and determine what causes the problem and whether it should be 1.0 or 1.1 and who should be assigned.

**Comment by JavierEspina** [comment]
> SDPi Friday 24 March Review: @d-gregorczyk will review issue and determine what causes the problem and whether it should be 1.0 or 1.1 and who should be assigned.

Sounds good. This has to be SDPi 1.0 as we cannot have normative text pointing to wrong places.

**Comment by ToddCooper** [comment]
Duplicates #53
