### ISSUE TITLE
Unclear conditionality of requirements in 2:B.3.4.2 & 2:B.4.4.2

### ISSUE THREAD

**Issue by JavierEspina** [IHE/DEV.SDPi#90]
## Section Number

2:B.3.4.2.2 PID-3 Patient Identifier List

## Priority

Medium

## Issue

All requirements in "2:B.3.4.2 PID - Patient Identification Segment" (except for R8102 and maybe R8109) should be conditional on the condition specified in R8102. That sounds like logical but will not be necessarily so when these requirements are extracted for conformance purposes.
The same comment applies to the parallel ACM section "2:B.4.4.2 PID - Patient Identification Segment"

## Proposed Change

Clarify in text

**Comment by d-gregorczyk** [comment]
Kathrin and I looked at the requirements and we do not see a need to add the condition. Here is why:

R8102 states:

> The SDC patient context information shall only be mapped to the corresponding fields in the HL7 PID segment when the requirements for a valid SDC patient context as defined in [IEEE 11073-10700] are fulfilled.

This prohibits mapping of patient context information if a patient context is not associated or not validated (which is also explained in the notes to R8102).

R8103 (and others that are affected) on the other side does not specify the conditions under which or when a mapping is to be performed but only the source and destination entities for the mapping:

> A SOMDS DEC Gateway / SOMDS ACM Gateway shall map the patient identifiers to the PID-3 field. 

This boils down to: no matter if, when or what, please map from patient identifiers to PID-3.
