### ISSUE TITLE
Wrong labels also for sections

### ISSUE THREAD

**Issue by JavierEspina** [IHE/DEV.SDPi#95]
## Section Number

2:B.3.4.6.5.3 Enumeration String Metric

## Priority

Low

## Issue

In R8022 text: "...shall map the identifier as described in section Appendix 2:B.4.3. -> Wrong labels also occur for Sections (not only for Tables). Please correct throughout (at least Vol2 Annex B). 

## Proposed Change

Ditto

**Comment by d-gregorczyk** [comment]
This issue stems from multiple includes of the same file in one document, which generates multiple ids with the same name such that the converter cannot uniquely relate to a section.

Once the gateway actors are generalized, this errors will disappear.
