### ISSUE TITLE
Response to Reviewer Question #2

### ISSUE THREAD

**Issue by JavierEspina** [IHE/DEV.SDPi#96]
## Section Number

2:B.3.4.6.13 OBX-18 Equipment Instance Identifier

## Priority

Low

## Issue
 "2.	Which unique VMD identifier are provided by devices?"
I would say that for (regulatory) device identification purposes a VMD is still a device, even when it is acting as part of another device. So I would expect the same kind of UDI for both. At least for those devices that can be removed from their parent device to "live" independently or within another parent....The challenge will be how to include in BICEPS a UDI for a VMD, as pm:Vmd does not support pm:MetaData (which in turn contains /pm:Udi)

## Proposed Change

N/A

**Comment by d-gregorczyk** [comment]
[This here](https://github.com/IHE/DEV.SDPi/pull/67) allows us to add identifiers to MDSs and VMDs. As I couldn't find an appropriate attribute / prod spec term in the nomenclature, I proceeded with an extension.

**Comment by ToddCooper** [comment]
SDPi Friday 24 March Review:  See issue #18  and PR #67 

@JavierEspina :  Verify that this issue is the same as #18  OR if it is different.

**Comment by JavierEspina** [comment]
> SDPi Friday 24 March Review: See issue #18 and PR #67
> 
> @JavierEspina : Verify that this issue is the same as #18 OR if it is different.

I think this issue (or rather a response to a REVIEWER QUESTION) is sufficiently covered by https://github.com/IHE/DEV.SDPi/issues/18. So I am going to close this one.
