### ISSUE TITLE
More clarity on advisory alerts

### ISSUE THREAD

**Issue by JavierEspina** [IHE/DEV.SDPi#97]
## Section Number

2:B.4.4.7.2.3 Technical Alerts

## Priority

Medium

## Issue

"2:B.4.4.7.2.3 Technical Alerts
The event identification mapping for a technical alert is.."
->What about advisory alerts? Shouldn´t they be added to this section title and first sentence description?
This comment also applies to section 2:B.4.4.7.3.2 Technical Alerts 

## Proposed Change

Clarify or add "/Advisory" to title and text

**Comment by JavierEspina** [comment]
@PeterKranich and @JavierEspina discussed this one on April 3. There is still uncertainty (in the A-PKP discussion) on how to handle advisories. Therefore this issue should be pushed to 1.1.

**Comment by AnnaFeiler** [comment]
@ToddCooper: I'd like to label that 1.x at the moment and wait for the APKP team to resolve their (our ;-) ) discussion

**Comment by AnnaFeiler** [comment]
@PeterKranich & @JavierEspina : This seems to be related to https://github.com/IHE/DEV.SDPi/issues/179. Can they be resolved together in 1.2?

**Comment by JavierEspina** [comment]
> @PeterKranich & @JavierEspina : This seems to be related to #179. Can they be resolved together in 1.2?

Yes, I think they are related. What I could not figure out is how the SDPi 1.2 Workshop conclusion on #179 impacts the resolution of this one. Maybe @PeterKranich can tell. And if not (yet), he and I should discuss this one in September

**Comment by ToddCooper** [comment]
**SDPi Workshop #3 2024.06.04**:  
Reviewed the issue & noted that #179 is now closed and merged.
@JavierEspina  @PeterKranich  will discuss and come back with a resolution.

**Comment by JavierEspina** [comment]
After looking in depth into this comment, I no longer see the issue. It may have been resolved by other changes over SDPi versions. So I withdraw my comment.
