### ISSUE TITLE
Inconsistent references to actors

### ISSUE THREAD

**Issue by d-gregorczyk** [IHE/DEV.SDPi#99]
## Section Number

* 10.1.1. Actor Descriptions and Actor Profile Requirements 
* Appendix B: Transaction Summary Definitions

## Priority

High - this impedes any corrections to the document that includes references to actors.

## Issue

The supplement contains two sections that introduce actor names, and both are randomly referenced within the volumes.

Moreover, there is no link between _Appendix B: Transaction Summary Definitions_ and _10.1.1. Actor Descriptions and Actor Profile Requirements_ (or at least I couldn't find any).

## Proposed Change

Identify to which section references should be drawn and apply changes to the entire document such that references are consistent again.

## Example

```asciidoc
.Actor Roles {var_transaction_id}
[cols="1,2"]
|===
|Actor |Roles

|<<vol1_spec_sdpi_p_actor_somds_provider>>
|Announces its presence by multicasting <<vol2_clause_dev_23_message_hello, {var_label_dev_23_message_hello}>> messages to all listening systems.

|<<actor_somds_consumer>>
|Listens for <<vol2_clause_dev_23_message_hello, {var_label_dev_23_message_hello}>> messages to identify any <<actor_somds_provider>>s that it may exchange messages with and further retrieve a <<actor_somds_provider>>'s service capabilities.

|===
```

The table on the one side references the consumer by using _actor_somds_consumer_, which is part of _Appendix B: Transaction Summary Definitions_. On the other side, it also references the provider by using _vol1_spec_sdpi_p_actor_somds_provider_, which is part of _10.1.1. Actor Descriptions and Actor Profile Requirements_.

**Comment by ToddCooper** [comment]
@d-gregorczyk  -- All TF-1 to TF-3 actor links should be to the TF-1 definition section anchors (e.g., [#vol1_spec_sdpi_p_actor_somds_provider, reftext='SOMDS Provider']).

**Comment by ToddCooper** [comment]
Closed inadvertently.
